---
chdir: "/home/master/apps/papermarketplace"
environment: production
address: 127.0.0.1
port: 3000
timeout: 30
log: "/home/master/apps/papermarketplace/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 3
daemonize: true
onebyone: true
ssl: true
